/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
export const angularTemplateHtml = `<ul class="pagination"><li *ngFor="let page of pages; trackBy: trackBy"><span *ngIf="page.disabled">{{page.text}}</span><a *ngIf="!page.disabled" href="javascript:void(0)" [class]="page.className" (click)="jumpTo(page.value)">{{page.text}}</a></li></ul>`;
