/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
export const vueTemplateHtml = `<ul class="pagination"><li v-for="page in pages" :key="page.text"><span v-if="page.disabled">{{page.text}}</span><a v-else href="javascript:void(0)" :class="page.className" @click="jumpTo(page.value)">{{page.text}}</a></li></ul>`;
